Repository DeveloperAcademy-POSTECH/MacC-Team-ALLWAY, pull requests merged in 2023-11, with the labels that each got.

#75 [Project] Deployment Target Update
  talklat/talklat.xcodeproj/project.pbxproj
Labels: 🛸 Projects

#76 Feat/#70 TKConversationView 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat.xcodeproj/xcshareddata/xcschemes/talklat.xcscheme
  talklat/talklat/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/CommunicationViewStore.swift
  talklat/talklat/Sources/Stores/ConversationViewStore.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTransitionTestView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/ScrollOffsetObserver.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/FullScreenCoverTesting/FullScreenCoverBottomView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/FullScreenCoverTesting/FullScreenCoverTesting.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/FullScreenCoverTesting/FullScreenCoverTextFieldView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/FullScreenCoverTesting/FullScreenCoverTopView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/ScrollContainerTesting/ScrollContainerBottomView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/ScrollContainerTesting/ScrollContainerTesting.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/ScrollContainerTesting/ScrollContainerTextFieldView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/ScrollContainerTesting/ScrollContainerTopView.swift
  talklat/talklat/Sources/Views/ScrollTestingViews/TestingTKHistoryView.swift
  talklat/talklat/Sources/Views/TKCommunicationView.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/Sources/Views/TestHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#81 Feat/#77 ScrollContainer와 TKConversationView를 연결
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/ConversationViewStore.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/ScrollOffsetObserver.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🐠 Lianne, 🌿 Celan

#93 Feat/#90 TKReducer lmpl
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Protocols/TKReducer.swift
  talklat/talklat/Sources/Stores/ConversationViewStore.swift
Labels: ✨ Feat, 🌿 Celan

#98 [Hotfix] `TKReducer` 의 기본 구현이었던 `callAsFunction` 을 제거(EXC_BAD_ACCESS)
  talklat/talklat/Sources/Protocols/TKReducer.swift
  talklat/talklat/Sources/Stores/ConversationViewStore.swift
Labels: 🐛 Bug, 🌿 Celan

#95 Feat/#86 TKConversation CRUD 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/ConversationDataManager.swift
  talklat/talklat/Sources/Stores/HistoryViewStore.swift
Labels: ✨ Feat, 🐠 Lianne

#74 Feat/#18 research speech recognition accelerate framework
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/History.swift
  talklat/talklat/Sources/Managers/SignalExtractor.swift
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Views/HistoryView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
Labels: ✨ Feat, 🥐 Madeline

#85 Feat/#71 implement location store
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/LocationStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/HistoryInfoItemView.swift
  talklat/talklat/Sources/Views/HistoryItemLocationEditView.swift
Labels: ✨ Feat, 🙃 Lets

#100 Feat/#92 TKMainView UI impl
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Protocols/TKReducer.swift
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TKBreathingCircles.swift
  talklat/talklat/Sources/Views/Components/TKOrbitCircles.swift
  talklat/talklat/Sources/Views/Components/TKTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/Sources/Views/TestHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#101 Feat/#94 HistoryList 관련 UIUX 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Models/SampleTKConversation.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/AWTextField.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/History/SearchBarView.swift
  talklat/talklat/Sources/Views/History/TKUnavailableViewBuilder.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🐠 Lianne

#103 Feat/#99 TKConversationView UI update
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Utilities/Extensions/EnvironmentValues+Namespace.swift
  talklat/talklat/Sources/Views/Components/TKColor.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTransitionTestView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#91 Feat/#87-Location-CRUD
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/History.swift
  talklat/talklat/Sources/Managers/LocationDataManager.swift
  talklat/talklat/Sources/Managers/SignalExtractor.swift
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Models/TKConversation.swift
  talklat/talklat/Sources/Protocols/TKReducer.swift
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/ConversationViewStore.swift
  talklat/talklat/Sources/Stores/LocationStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TKBreathingCircles.swift
  talklat/talklat/Sources/Views/Components/TKOrbitCircles.swift
  talklat/talklat/Sources/Views/Components/TKTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/HistoryInfoItemView.swift
  talklat/talklat/Sources/Views/HistoryItemLocationEditView.swift
  talklat/talklat/Sources/Views/HistoryView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/Sources/Views/TestHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🙃 Lets

#105 Feat/#84 SwiftData Manager & Store 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/DataTestingView.swift
  talklat/talklat/Sources/Managers/LocationDataManager.swift
  talklat/talklat/Sources/Managers/TKDataManager.swift
  talklat/talklat/Sources/Managers/TKSwiftDataStore.swift
  talklat/talklat/Sources/Models/SampleTKConversation.swift
  talklat/talklat/Sources/Models/TKContent.swift
  talklat/talklat/Sources/Models/TKConversation.swift
  talklat/talklat/Sources/Models/TKLocation.swift
  talklat/talklat/Sources/Models/TKTextReplacement.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: ✨ Feat, 🐠 Lianne

#111 [Refactor/#107] HistoryListView, SearchView에 SwiftData 연결
  talklat/talklat/Sources/Managers/DataTestingView.swift
  talklat/talklat/Sources/Managers/TKDataManager.swift
  talklat/talklat/Sources/Managers/TKSwiftDataStore.swift
  talklat/talklat/Sources/Models/TKContent.swift
  talklat/talklat/Sources/Models/TKConversation.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🐠 Lianne

#82 Feat/#80 Speech transcript add punctuation
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/CommunicationViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/TKCommunicationView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🥐 Madeline

#104 Feat/#88 Implement HistoryView inside
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Models/ChatMessage.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/Date+Formatter.swift
  talklat/talklat/Sources/Views/CustomHistoryView.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/ChatMessageCell.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/CustomHistoryViewControllerRepresentable.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/CustomTableViewController.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/HistoryViewController.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/SectionHeaderView.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/SheetWebView.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
Labels: ✨ Feat, 🙃 Lets

#96 Feat/#79 텍스트 대치 기능만! text replacement, CRU in SwiftData
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/TKTextReplacementManager.swift
  talklat/talklat/Sources/Models/TKTextReplacement.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/Conversation/TestTKSettingView.swift
Labels: ✨ Feat, 🥐 Madeline

#112 Feat/#97 TextReplacement CRUD 관련 뷰 UI와 기능 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/TKTextReplacementManager.swift
  talklat/talklat/Sources/Models/TKTextReplacement.swift
  talklat/talklat/Sources/Stores/SettingViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/Character+Consonant.swift
  talklat/talklat/Sources/Utilities/Extensions/String+Language.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/Settings/SectionIndexTitles.swift
  talklat/talklat/Sources/Views/Settings/SettingTRTextField.swift
  talklat/talklat/Sources/Views/Settings/TKTextReplacementAddView.swift
  talklat/talklat/Sources/Views/Settings/TKTextReplacementEditView.swift
  talklat/talklat/Sources/Views/Settings/TKTextReplacementListView.swift
  talklat/talklat/Sources/Views/Settings/TextReplacementRow.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🥐 Madeline

#117 Feat/#114 TKToast, TKAlert Component 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/SpeechAuthManager.swift
  talklat/talklat/Sources/Stores/CommunicationViewStore.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Components/TKToast.swift
Labels: ✨ Feat, 🌿 Celan

#113 Feedback/#106 TKMain, TKConversationView feedback 반영
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/TKBubble_Main.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TKBubble_Main.imageset/TKBubble_Main.png
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Views/Components/TKOrbitCircles.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
Labels: ✨ Feat, 🌿 Celan

#127 Feat/#126 TKSplashView 및 Asset 추가
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  talklat/talklat/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/AppIcon.appiconset/talklat.png
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE.imageset/TALKLAT_BUBBLE.svg
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/TALKLAT_BUBBLE_WHITE.svg
  talklat/talklat/Resources/Assets.xcassets/TKBubble_Main.imageset/TKBubble_Main.png
  talklat/talklat/Resources/Assets.xcassets/Talklat_Typo.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Talklat_Typo.imageset/TALKLAT_TYPO.svg
  talklat/talklat/Sources/Views/Components/TKSplashView.swift
  talklat/talklat/Sources/Views/HistoryItemLocationEditView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#136 Feat/#131 TKOnboardingView UI 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/TALKALT_BUBBLES_MARK.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKALT_BUBBLES_MARK.imageset/TALKALT_BUBBLES_MARK.svg
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingAuthReqeustView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingView.swift
Labels: ✨ Feat, 🌿 Celan

#144 Fix/#142-ChatMessageDarkModeFix
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/CustomHistoryViewController/ChatMessageCell.swift
Labels: ✨ Feat, 🙃 Lets

#151 Fix/#148 TKTextReplacementListCell UI fix
  talklat/talklat/Sources/Stores/TextReplacementViewStore.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/SettingTRSearchBar.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementEditView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementListView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementSearchView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#153 [Ver1.0.0] ..!
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Views/Components/TKOrbitCircles.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKHistoryView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/SearchBarView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsTeamView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TextReplacementRow.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🛸 Projects, 🐠 Lianne, 🥐 Madeline, 🙃 Lets, 🌿 Celan, 🪄 Fix

#161 [Feat/#152] Text Design System 구현
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/DesignSystem/BDText.swift
Labels: ✨ Feat, 🥐 Madeline

#171 Merge/#138 ver 1.0.0 build 23112116
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
Labels: 🛸 Projects, 🌿 Celan, 🚨ReleasePrep

#175 Fix/#169 Settings 접근성 (화면 모드) 수정 작업
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/Colors/AlertBGWhite.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/BaseBGWhite.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR1.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR2.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR3.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR4.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR5.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR6.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR7.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR8.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR9.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/OR5.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/OR6.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/RED.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/SheetBGWhite.colorset/Contents.json
  talklat/talklat/Sources/Managers/ColorSchemeManager.swift
  talklat/talklat/Sources/Views/Components/BDListCell.swift
  talklat/talklat/Sources/Views/Components/TKColor.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsAppInfoView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsDisplayTestingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsDisplayView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsGestureView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHapticView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHelpView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/talklatApp.swift
Labels: 🐠 Lianne, 🪄 Fix

#176 Feat/#170 Settings 실험실 (플립 제스쳐 on/off) 작업
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsGestureView.swift
Labels: ✨ Feat, 🐠 Lianne

#178 Fix/#173 transcript answered text assign bug fix
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Views/Components/TKOrbitCircles.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
Labels: 🐛 Bug, 🌿 Celan, 🪄 Fix

#167 Fix/#160 fix custom history view
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/TKDataManager.swift
  talklat/talklat/Sources/Stores/TKSwiftDataStore.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/HistoryViewController.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
Labels: 🙃 Lets, 🪄 Fix

#172 Feat/#157 OnboardingView Impl
  talklat/talklat/Sources/Managers/TKAuthManager.swift
  talklat/talklat/Sources/Stores/TKLocationStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingAuthReqeustView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#174 Feat/#168 insert tk draggable list content
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/none.talk.light.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/none.talk.light.imageset/none.talk.light.png
  talklat/talklat/Sources/Stores/TKLocationStore.swift
  talklat/talklat/Sources/Utilities/Extensions/OptionalInt+Distance.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/CustomTableViewController.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/SectionHeaderView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/HistoryInfoItemView.swift
  talklat/talklat/Sources/Views/HistoryItemLocationEditView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
Labels: ✨ Feat, 🙃 Lets

#165 Fix/#164 Settings and MainView UI 디자인 수정
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/history_symbol_dark.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/history_symbol_dark.imageset/history_symbol_dark.svg
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/history_symbol_light.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/history_symbol_light.imageset/history_symbol_light.svg
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/settings_symbol_dark.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/settings_symbol_dark.imageset/settings_symbol_dark.svg
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/settings_symbol_light.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/settings_symbol_light.imageset/settings_symbol_light.svg
  talklat/talklat/Resources/Assets.xcassets/TeamLogo_Dark.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TeamLogo_Dark.imageset/TeamLogo_Dark.svg
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo_Dark.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo_Dark.imageset/bisdam_typo_Dark.svg
  talklat/talklat/Sources/Utilities/Extensions/View+SwipeGesture.swift
  talklat/talklat/Sources/Views/Components/TKListCell.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Settings_/EmailView.swift
  talklat/talklat/Sources/Views/Settings_/LoadingWebView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHelpView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsTeamView.swift
Labels: 🥐 Madeline, 🪄 Fix

#180 Feat/#152 Font Pretendard 추가 및 디자인시스템 Fix
  talklat/bisdam-Info.plist
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/DesignSystem/BDText.swift
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Black.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Bold.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-ExtraBold.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-ExtraLight.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Light.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Medium.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Regular.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-SemiBold.otf
  talklat/talklat/Sources/Views/Components/DesignSystem/Fonts/Pretendard-Thin.otf
Labels: ✨ Feat, 🥐 Madeline, ☕️ Moca, 🪄 Fix

#182 Fix/#166 ConversationView 관련 UI 디자인 수정
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
Labels: ✨ Feat, 🥐 Madeline, ☕️ Moca, 🪄 Fix

#193 Fix/#190 TKTypingView Toolbar & UI BugFix
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/bisdam.xcodeproj/xcshareddata/xcschemes/bisdam.xcscheme
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Stores/TextReplacementViewStore.swift
  talklat/talklat/Sources/Utilities/Extensions/View+TKAlert.swift
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Components/TKColor.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementEditView.swift
  talklat/talklat/talklatApp.swift
Labels: 🌿 Celan, 🪄 Fix

#195 Feat/#184 TKAlert UI Update
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
Labels: ✨ Feat, 🌿 Celan

#194 Feat/#187 custom history view add connection
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKDraggableListViewStore.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
Labels: ✨ Feat, 🙃 Lets, 🪄 Fix

#185 Fix/#158 1.0.0 Settings에서 제외된 부분 추가
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/Colors/AlertBGWhite.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/BaseBGWhite.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR1.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR2.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR3.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR4.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR5.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR6.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR7.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR8.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/GR9.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/OR5.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/OR6.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/RED.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Colors/SheetBGWhite.colorset/Contents.json
  talklat/talklat/Sources/DEPRECATED/SettingsAppInfoView.swift
  talklat/talklat/Sources/DEPRECATED/SpeechAuthManager.swift
  talklat/talklat/Sources/Managers/ColorSchemeManager.swift
  talklat/talklat/Sources/Managers/TKAuthManager.swift
  talklat/talklat/Sources/Views/Components/BDListCell.swift
  talklat/talklat/Sources/Views/Components/TKColor.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Settings_/DataPolicyInfo/LoadingWebView.swift
  talklat/talklat/Sources/Views/Settings_/DataPolicyInfo/WebView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingPreView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsDisplayTestingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsDisplayView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsGestureView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHapticView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHelpView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🐠 Lianne, 🪄 Fix

#188 Fix/#183 historylist view UI 디자인 수정
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/History/SearchBarView.swift
Labels: 🥐 Madeline, 🪄 Fix

#191 Fix/#186 HistoryListView 관련 기능 수정
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/TKSwiftDataStore.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/History/SearchBarView.swift
Labels: 🐠 Lianne, 🪄 Fix

#205 Feat/#204 SplashView Lottie apply
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/bisdam.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  talklat/bisdam.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  talklat/talklat/Resources/BDSplash.json
  talklat/talklat/Sources/Views/Components/TKSplashView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#203 Fix/#181 history detail qa
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/TKHistoryInfoStore.swift
  talklat/talklat/Sources/Stores/TKSwiftDataStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/Coordinate+Equatble.swift
  talklat/talklat/Sources/Utilities/Extensions/Double+Degree.swift
  talklat/talklat/Sources/Views/CustomHistoryView.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/CustomTableViewController.swift
  talklat/talklat/Sources/Views/CustomHistoryViewController/HistoryViewController.swift
  talklat/talklat/Sources/Views/HistoryInfoItemView.swift
Labels: 🙃 Lets, 🪄 Fix

#202 Fix/#199 fix text to bdtext designsystem
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/CustomAlertView.swift
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Components/TKToast.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKHistoryView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/CustomHistoryView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingAuthReqeustView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHapticView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsTeamView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/SettingTRTextField.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementAddView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementEditView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementListView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TextReplacementRow.swift
Labels: 🥐 Madeline, 🪄 Fix

#207 Hot fix/#201 HistoryList 관련 QA 결과 반영
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/TKDataManager.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/Settings_/DataPolicyInfo/LoadingWebView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingPreView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsDisplayView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHapticView.swift
  talklat/talklat/talklatApp.swift
Labels: 🐛 Bug, 🐠 Lianne, 🪄 Fix

#206 Update/#200 ver1.1.0 Release QA's
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/none.talk.light.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/CustomSymbol/none.talk.light.imageset/none.talk.light.svg
  talklat/talklat/Resources/Assets.xcassets/none.talk.light.imageset/none.talk.light.png
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Managers/TKAuthManager.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKDraggableListViewStore.swift
  talklat/talklat/Sources/Stores/TKSwiftDataStore.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/Main/TKDraggableList.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingView.swift
  talklat/talklat/Sources/Views/Settings_/DataPolicyInfo/LoadingWebView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings_/Guiding/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsGestureView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsHelpView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings_/SettingsTeamView.swift
  talklat/talklat/Sources/Views/Settings_/TextReplacement/TKTextReplacementListView.swift
Labels: 🐠 Lianne, 🥐 Madeline, 🙃 Lets, 🌿 Celan, ☕️ Moca, 🚨ReleasePrep
