Repository DeveloperAcademy-POSTECH/MacC-Team-ALLWAY, pull requests merged in 2023-10, with the labels that each got.

#6 [init] Project Init
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  talklat/talklat.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  talklat/talklat/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Contents.json
  talklat/talklat/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  talklat/talklat/Sources/Views/ContentView.swift
  talklat/talklat/talklatApp.swift
  talklat/talklatTests/talklatTests.swift
  talklat/talklatUITests/talklatUITests.swift
  talklat/talklatUITests/talklatUITestsLaunchTests.swift
Labels: 🛸 Projects

#10 [Feat/#9] SpeechToText Authorization Handling
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/AppRootManager.swift
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Views/AuthorizationRequestView.swift
  talklat/talklat/Sources/Views/HandlingTestingView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🐠 Lianne

#11 [Feat/#7] CoreMotion 으로 flip 상태 표시 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/GyroScopeStore.swift
Labels: ✨ Feat, 🙃 Lets

#12 [Feat/#8] SpeechRecognizer 기능 구현, SampleView
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat.xcodeproj/xcshareddata/xcschemes/talklat.xcscheme
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Views/HandlingTestingView.swift
  talklat/talklat/Sources/Views/StaffSpeechView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🥐 Madeline

#13 Feat/#4 UI layout animatiion
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TKTextField.swift
  talklat/talklat/Sources/Views/ContentView.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#19 Feat/#14 UI와 기능 간 연결 진행
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/AppRootManager.swift
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/GyroScopeStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/Double+Degree.swift
  talklat/talklat/Sources/Views/AuthorizationRequestView.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#25 #feat/24 advanced gyro feature
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/GyroScopeStore.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
Labels: ✨ Feat, 🙃 Lets

#32 Fix/#26 QuestionText와 GuidingMessage 관련 UX/UI 수정 작업
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: 🐛 Bug, 🌿 Celan

#33 Feat/#28 implement haptic feedback
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Managers/HapticManager.swift
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
Labels: ✨ Feat, 🙃 Lets

#35 Feat/#31 TKHistoryView를 구현합니다.
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/TKHistoryView.swift
Labels: ✨ Feat, 🌿 Celan

#39 Feat/#30 feat historyview conversation
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Stores/GyroScopeStore.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/Sources/Views/TestHistoryView.swift
Labels: ✨ Feat, 🥐 Madeline

#29 Feat/#17 textfield design system
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/TLTextField.swift
Labels: ✨ Feat, 🥐 Madeline

#40 Feat/#38 color design system 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Utilities/Extensions/Color+Hex.swift
  talklat/talklat/Sources/Views/Components/TKColor.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
Labels: ✨ Feat, 🌿 Celan

#34 Feat/#27 implement live haptic feedback
  talklat/talklat/Sources/Managers/HapticManager.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: ✨ Feat, 🙃 Lets

#43 Feat/#42 TKHistoryView와 HistoryItems 연동
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: ✨ Feat, 🌿 Celan

#44 Feat/#36 뷰 스크롤 트랜지션 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/SwipeGuideMessage.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 📦 Todo, 🐠 Lianne

#45 Feat/#41 refactoring tkhistoryview
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Models/HistoryItem.swift
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/View+Keyboard.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/TKHistoryView.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
  talklat/talklat/Sources/Views/TestHistoryView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🥐 Madeline

#53 Fix/#48 fix button malfunction
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: 🐛 Bug, 🌿 Celan

#57 [Fix/#55] TKRecordingview-Subtle-Bugfix
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
Labels: 🐛 Bug, 🌿 Celan

#62 Hotfix/#60 internal showcase quick feedback
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/TKWritingView.swift
Labels: ✨ Feat, 🌿 Celan

#64 [Feat/#52] 음성인식 2번째 이후 가이딩메세지 추가
  talklat/talklat/Sources/Stores/AppViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/TKRecordingView.swift
Labels: ✨ Feat, 🥐 Madeline

#68 Proj/#67 GitHub template adjust
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛸 Projects, 🌿 Celan

#65 Feat/#63 TKCommunicationView 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Models/HistoryItem.swift
  talklat/talklat/Sources/Stores/CommunicationViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/ScrollContainer.swift
  talklat/talklat/Sources/Views/TKCommunicationView.swift
  talklat/talklat/Sources/Views/TKIntroView.swift
  talklat/talklat/talklatApp.swift
Labels: ✨ Feat, 🌿 Celan

#72 Feat/#69 TKGuidingView 구현
  talklat/talklat.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/TKGuidingView.swift
Labels: ✨ Feat, 🌿 Celan
