Repository DeveloperAcademy-POSTECH/MacC-Team-ALLWAY, pull requests merged in 2024-04, with the labels that each got.

#231 [Fix/#228] ConversationView 디자인 QA 내역 반영
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Components/DesignSystem/BDText.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Components/TLTextField.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
Labels: 🐠 Lianne, 🪄 Fix

#237 Update/#236 conversation guiding message update
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingPreView.swift
Labels: 🪄 Fix

#235 Fix/#233 conversation stt flow fix
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Views/Components/TKScrollView.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
Labels: 🪄 Fix

#239 Feat/#234 Localization 전체 범위, 관련 QA 픽스
  talklat/InfoPlist.xcstrings
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/bisdam.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  talklat/bisdam.xcodeproj/xcshareddata/xcschemes/bisdam.xcscheme
  talklat/talklat/Localizable.xcstrings
  talklat/talklat/Sources/Managers/SpeechRecognizer.swift
  talklat/talklat/Sources/Stores/TKConversationViewStore.swift
  talklat/talklat/Sources/Stores/TKHistoryInfoStore.swift
  talklat/talklat/Sources/Stores/TKLocationStore.swift
  talklat/talklat/Sources/Stores/TKMainViewStore.swift
  talklat/talklat/Sources/Utilities/Constants.swift
  talklat/talklat/Sources/Utilities/Extensions/Date+Formatter.swift
  talklat/talklat/Sources/Utilities/Extensions/OptionalInt+Distance.swift
  talklat/talklat/Sources/Views/Components/TKAlert.swift
  talklat/talklat/Sources/Views/Components/TKToast.swift
  talklat/talklat/Sources/Views/Conversation/TKConversationView.swift
  talklat/talklat/Sources/Views/Conversation/TKGuidingView.swift
  talklat/talklat/Sources/Views/Conversation/TKHistoryView.swift
  talklat/talklat/Sources/Views/Conversation/TKListeningView.swift
  talklat/talklat/Sources/Views/Conversation/TKSavingView.swift
  talklat/talklat/Sources/Views/Conversation/TKTypingView.swift
  talklat/talklat/Sources/Views/CustomHistoryView.swift
  talklat/talklat/Sources/Views/History/HistoryListSearchView.swift
  talklat/talklat/Sources/Views/History/HistoryListView.swift
  talklat/talklat/Sources/Views/History/SearchBarView.swift
  talklat/talklat/Sources/Views/History/TKUnavailableViewBuilder.swift
  talklat/talklat/Sources/Views/HistoryInfoItemView.swift
  talklat/talklat/Sources/Views/HistoryItemLocationEditView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/Sources/Views/Main/TKRecentConversationListView.swift
  talklat/talklat/Sources/Views/Onboarding/TKOnboardingView.swift
  talklat/talklat/Sources/Views/Settings/DataPolicyInfo/LoadingWebView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingPreView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings/SettingsDisplayView.swift
  talklat/talklat/Sources/Views/Settings/SettingsGestureView.swift
  talklat/talklat/Sources/Views/Settings/SettingsHapticView.swift
  talklat/talklat/Sources/Views/Settings/SettingsHelpView.swift
  talklat/talklat/Sources/Views/Settings/SettingsListView.swift
  talklat/talklat/Sources/Views/Settings/SettingsTeamView.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/SettingTRSearchBar.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/SettingTRTextField.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/TKTextReplacementAddView.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/TKTextReplacementEditView.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/TKTextReplacementListView.swift
  talklat/talklat/Sources/Views/Settings/TextReplacement/TKTextReplacementSearchView.swift
Labels: ✨ Feat, 🐠 Lianne, 🥐 Madeline

#248 Deploy/#238 ver 120
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/bisdam.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  talklat/bisdam.xcodeproj/xcshareddata/xcschemes/bisdam.xcscheme
  talklat/talklat/Resources/Assets.xcassets/TALKALT_BUBBLES_MARK.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKALT_BUBBLES_MARK.imageset/TALKALT_BUBBLES_MARK.svg
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE.imageset/TALKLAT_BUBBLE.svg
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/TALKLAT_BUBBLE_WHITE.png
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/TALKLAT_BUBBLE_WHITE.svg
  talklat/talklat/Resources/Assets.xcassets/Talklat_Typo.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/Talklat_Typo.imageset/TALKLAT_TYPO.svg
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo.imageset/bisdam_typo.png
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo_Dark.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/bisdam_typo_Dark.imageset/bisdam_typo_Dark.png
  talklat/talklat/Sources/Utilities/Extensions/View+LocalizeLogoFrame.swift
  talklat/talklat/Sources/Views/Components/TKSplashView.swift
  talklat/talklat/Sources/Views/Main/TKMainView.swift
  talklat/talklat/talklatApp.swift
Labels: 🐠 Lianne, 🥐 Madeline, 🙃 Lets, 🌿 Celan, 🚨ReleasePrep

#254 [Asset/#253] Bubble Asset이 깨지는 현상 수정
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/Contents.json
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/TALKLAT_BUBBLE_WHITE.png
  talklat/talklat/Resources/Assets.xcassets/TALKLAT_BUBBLE_WHITE.imageset/TALKLAT_BUBBLE_WHITE.svg
Labels: 🪄 Fix

#255 Fix/#251 settings UI fix
  talklat/bisdam.xcodeproj/project.pbxproj
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingEditView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingPreView.swift
  talklat/talklat/Sources/Views/Settings/Guiding/SettingsGuidingView.swift
  talklat/talklat/Sources/Views/Settings/SettingsListView.swift
Labels: 🐛 Bug

#257 [Fix/#256] 개인정보처리방침 로컬라이제이션 대응
  talklat/bisdam.xcodeproj/xcshareddata/xcschemes/bisdam.xcscheme
  talklat/talklat/Localizable.xcstrings
  talklat/talklat/Sources/Views/Settings/DataPolicyInfo/LoadingWebView.swift
Labels: 🪄 Fix

#258 [Deploy/#238]
  talklat/bisdam.xcodeproj/project.pbxproj
Labels: 🚨ReleasePrep
